services:
  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    env_file:
      - ./toucans/settings/.postgres.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: toucans-db
    hostname: toucans-db
    networks:
      - internal

  web-service:
    image: ghcr.io/davidjrichardson/toucans:2023-03-05
    depends_on:
      - db
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./toucans/settings/.toucans.env
    environment:
      - DB_HOST=toucans-db
    container_name: toucans-web-service
    hostname: toucans-web-service
    networks:
      - internal
      - external

networks:
  internal:
  external: