# Generated by Django 2.1.4 on 2018-12-31 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0003_auto_20181230_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('menu_order', models.IntegerField(help_text='This number decides where in the top navigation the page will appear, lower is further left', verbose_name='Menubar Item Ordering')),
                ('menu_title', models.CharField(help_text="The page title as you'd like it to be seen by the public in the menu bar", max_length=255, verbose_name='Menubar Title')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
