# Generated by Django 2.1.7 on 2019-03-06 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0023_auto_20190306_1651"),
    ]

    operations = [
        migrations.RenameField(
            model_name="standingsentry",
            old_name="leg1_golds",
            new_name="leg_1_golds",
        ),
        migrations.RenameField(
            model_name="standingsentry",
            old_name="leg1_hits",
            new_name="leg_1_hits",
        ),
        migrations.RenameField(
            model_name="standingsentry",
            old_name="leg1_score",
            new_name="leg_1_score",
        ),
    ]
