# Generated by Django 2.1.7 on 2019-03-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_auto_20190306_1657"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standingsentry",
            name="leg_1_golds",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="standingsentry",
            name="leg_1_hits",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="standingsentry",
            name="leg_1_score",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="standingsentry",
            name="leg_2_golds",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="standingsentry",
            name="leg_2_hits",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="standingsentry",
            name="leg_2_score",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="standingsentry",
            name="leg_3_golds",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="standingsentry",
            name="leg_3_hits",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="standingsentry",
            name="leg_3_score",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="standingsentry",
            name="leg_4_golds",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="standingsentry",
            name="leg_4_hits",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="standingsentry",
            name="leg_4_score",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="standingsentry",
            name="leg_5_golds",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="standingsentry",
            name="leg_5_hits",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="standingsentry",
            name="leg_5_score",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
