# Generated by Django 2.1.7 on 2019-03-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0027_auto_20190307_1412"),
    ]

    operations = [
        migrations.RenameField(
            model_name="standingsentry",
            old_name="university",
            new_name="team_name",
        ),
        migrations.AddField(
            model_name="standingsentry",
            name="team_is_novice",
            field=models.BooleanField(default=False),
        ),
    ]
