# Generated by Django 2.1.7 on 2019-03-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20190307_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standingsentry',
            name='champs_golds',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='standingsentry',
            name='champs_hits',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='standingsentry',
            name='champs_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='standingsentry',
            name='leg_1_golds',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='standingsentry',
            name='leg_1_hits',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='standingsentry',
            name='leg_1_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='standingsentry',
            name='leg_2_golds',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='standingsentry',
            name='leg_2_hits',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='standingsentry',
            name='leg_2_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='standingsentry',
            name='leg_3_golds',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='standingsentry',
            name='leg_3_hits',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='standingsentry',
            name='leg_3_score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='standingsentry',
            name='leg_4_golds',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='standingsentry',
            name='leg_4_hits',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='standingsentry',
            name='leg_4_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
