# Generated by Django 2.1.7 on 2019-03-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_genericpage_genericrelatedlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericpage',
            name='description',
        ),
    ]
