# Generated by Django 2.1.7 on 2019-04-09 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20190409_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badgespage',
            name='genericpage_ptr',
        ),
        migrations.AddField(
            model_name='badgespage',
            name='resourcepage_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.ResourcePage'),
            preserve_default=False,
        ),
    ]
