# Generated by Django 2.2.5 on 2019-09-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20190409_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='bb_black_score',
            field=models.IntegerField(verbose_name='BB Black'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='bb_blue_score',
            field=models.IntegerField(verbose_name='BB Blue'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='bb_gold_score',
            field=models.IntegerField(verbose_name='BB Gold'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='bb_red_score',
            field=models.IntegerField(verbose_name='BB Red'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='bb_white_score',
            field=models.IntegerField(verbose_name='BB White'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='cb_black_score',
            field=models.IntegerField(verbose_name='CP Black'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='cb_blue_score',
            field=models.IntegerField(verbose_name='CP Blue'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='cb_gold_score',
            field=models.IntegerField(verbose_name='CP Gold'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='cb_red_score',
            field=models.IntegerField(verbose_name='CP Red'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='cb_white_score',
            field=models.IntegerField(verbose_name='CP White'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='lb_black_score',
            field=models.IntegerField(verbose_name='LB Black'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='lb_blue_score',
            field=models.IntegerField(verbose_name='LB Blue'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='lb_gold_score',
            field=models.IntegerField(verbose_name='LB Gold'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='lb_red_score',
            field=models.IntegerField(verbose_name='LB Red'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='lb_white_score',
            field=models.IntegerField(verbose_name='LB White'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='rc_black_score',
            field=models.IntegerField(verbose_name='RC Black'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='rc_blue_score',
            field=models.IntegerField(verbose_name='RC Blue'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='rc_gold_score',
            field=models.IntegerField(verbose_name='RC Gold'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='rc_red_score',
            field=models.IntegerField(verbose_name='RC Red'),
        ),
        migrations.AlterField(
            model_name='leaguebadgeroundentry',
            name='rc_white_score',
            field=models.IntegerField(verbose_name='RC White'),
        ),
    ]
