# Generated by Django 2.2.5 on 2019-09-05 10:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("wagtailforms", "0003_capitalizeverbose"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("home", "0050_auto_20190905_1024"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewStandingsEntry",
            new_name="ThreeLegStandingsEntry",
        ),
        migrations.RenameModel(
            old_name="NewStandingsPage",
            new_name="ThreeLegStandingsPage",
        ),
    ]
