# Generated by Django 4.2.15 on 2024-08-21 14:12

import common.fields
import common.models
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_alter_threelegstandingsentry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionOneStandingsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('team_name', models.CharField(max_length=50)),
                ('exp_leg_1', common.fields.ArcheryLegResultField(default=common.models.leg_results_field_default)),
                ('exp_leg_2', common.fields.ArcheryLegResultField(default=common.models.leg_results_field_default)),
                ('exp_leg_3', common.fields.ArcheryLegResultField(default=common.models.leg_results_field_default)),
                ('exp_champs', common.fields.ArcheryLegResultField(default=common.models.leg_results_field_default)),
                ('nov_leg_1', common.fields.ArcheryLegResultField(default=common.models.leg_results_field_default)),
                ('nov_leg_2', common.fields.ArcheryLegResultField(default=common.models.leg_results_field_default)),
                ('nov_leg_3', common.fields.ArcheryLegResultField(default=common.models.leg_results_field_default)),
                ('nov_champs', common.fields.ArcheryLegResultField(default=common.models.leg_results_field_default)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='div1_results', to='home.threelegstandingspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ThreeLegStandingsEntry',
        ),
    ]
