# Generated by Django 4.2.16 on 2024-11-29 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0061_divisiontwostandingsentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="legacyfourlegstandingspage",
            name="end_year",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 11, 29, 21, 13, 56, 464963, tzinfo=datetime.timezone.utc
                ),
                help_text="The end date of the league. Can be approximate if it is not totally certain.",
                verbose_name="End date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="legacyfourlegstandingspage",
            name="start_year",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 11, 29, 21, 13, 58, 984434, tzinfo=datetime.timezone.utc
                ),
                help_text="The start date of the league",
                verbose_name="Start date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="legacythreelegstandingspage",
            name="end_year",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 11, 29, 21, 14, 0, 176376, tzinfo=datetime.timezone.utc
                ),
                help_text="The end date of the league. Can be approximate if it is not totally certain.",
                verbose_name="End date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="legacythreelegstandingspage",
            name="start_year",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 11, 29, 21, 14, 1, 545473, tzinfo=datetime.timezone.utc
                ),
                help_text="The start date of the league",
                verbose_name="Start date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="threelegstandingspage",
            name="end_year",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 11, 29, 21, 14, 3, 31910, tzinfo=datetime.timezone.utc
                ),
                help_text="The end date of the league. Can be approximate if it is not totally certain.",
                verbose_name="End date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="threelegstandingspage",
            name="start_year",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 11, 29, 21, 14, 4, 540082, tzinfo=datetime.timezone.utc
                ),
                help_text="The start date of the league",
                verbose_name="Start date",
            ),
            preserve_default=False,
        ),
    ]
