# Generated by Django 4.2.16 on 2024-11-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0062_legacyfourlegstandingspage_end_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legacyfourlegstandingspage",
            name="standings_year",
            field=models.TextField(
                blank=True,
                help_text="The academic year for this set of standings",
                null=True,
                verbose_name="Academic year",
            ),
        ),
        migrations.AlterField(
            model_name="legacythreelegstandingspage",
            name="standings_year",
            field=models.TextField(
                blank=True,
                help_text="The academic year for this set of standings",
                null=True,
                verbose_name="Academic year",
            ),
        ),
        migrations.AlterField(
            model_name="threelegstandingspage",
            name="standings_year",
            field=models.TextField(
                blank=True,
                help_text="The academic year for this set of standings",
                null=True,
                verbose_name="Academic year",
            ),
        ),
    ]
