# Generated by Django 4.2.16 on 2024-11-29 21:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0063_alter_legacyfourlegstandingspage_standings_year_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="legacyfourlegstandingspage",
            old_name="end_year",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="legacyfourlegstandingspage",
            old_name="start_year",
            new_name="start_date",
        ),
        migrations.RenameField(
            model_name="legacythreelegstandingspage",
            old_name="end_year",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="legacythreelegstandingspage",
            old_name="start_year",
            new_name="start_date",
        ),
        migrations.RenameField(
            model_name="threelegstandingspage",
            old_name="end_year",
            new_name="end_date",
        ),
        migrations.RenameField(
            model_name="threelegstandingspage",
            old_name="start_year",
            new_name="start_date",
        ),
    ]
