# Generated by Django 4.2.19 on 2025-02-15 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
        ('home', '0064_rename_end_year_legacyfourlegstandingspage_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standingsindexpage',
            name='latest_year_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
