# Generated by Django 4.2.19 on 2025-09-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0065_standingsindexpage_latest_year_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="footer",
            name="instagram_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
